### PR TITLE
[GH-696] Allow clients to modify tickrate

### LINKED ISSUE #696: Allow client to modify the TICKRATE

### PR DESCRIPTION
**Pull request by Nico-Sanchez**
> [!IMPORTANT]  
> This PR must be merged along with https://github.com/lambdaclass/champions_of_mirra/pull/1842

## Motivation

We must allow clients to modify the game tickrate.
Closes #696 

## Summary of changes

- [Add new ChangeTickrate protobuf message](https://github.com/lambdaclass/mirra_backend/pull/704/commits/13201761fa55dce4cd4a91542f060e3b84e06a66)
- [Add new handle_decoded_message matches functions to print unexpected messages in terminal](https://github.com/lambdaclass/mirra_backend/pull/704/commits/71028a2029544ac969f4972d52bc61373eb88470)
- [Add new change_tickrate function and cast handler to modify the game tickrate](https://github.com/lambdaclass/mirra_backend/pull/704/commits/0f399b9eb8135bdb43d0134d481e3286e4ee4c8e)
- [Add new handle_decoded_message to catch change_tickrate message and call the corresponding function](https://github.com/lambdaclass/mirra_backend/pull/704/commits/d0c03b8d547892337dc889af6de013b491a13d35)

## How to test it?

Play a game with the following client branch -> https://github.com/lambdaclass/champions_of_mirra/pull/1842
Change the game TICKRATE using the slider in settings > dev tab > Tickrate.

## Checklist
- [x] Tested the changes locally.
- [x] Reviewed the changes on GitHub, line by line.
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.

### CODE REVIEW

**Review by tvillegas98 — COMMENTED** [review]
I don't know the reason but we're not receiving the messages to change the tickrate. I tried inspecting the value received from the client and it doesn't seem to work.
Added prints in 
`apps/arena/lib/arena/game_updater.ex:51`
`apps/arena/lib/arena/game_updater.ex:174`

**Comment by Nico-Sanchez** [comment]
> I don't know the reason but we're not receiving the messages to change the tickrate. I tried inspecting the value received from the client and it doesn't seem to work. Added prints in `apps/arena/lib/arena/game_updater.ex:51` `apps/arena/lib/arena/game_updater.ex:174`

This was due to a bug in the client PR, I already pushed a fix!

**Review by tvillegas98 — APPROVED** [review]
Seems to work fine!

**Review by agustinesco — CHANGES_REQUESTED** [review]
Testing this pr i couldn't make the tickrate be slower with the slider. On this video i'm printing `time_diff = (now - game_state.server_timestamp) |> IO.inspect(label: "Aber time diff")` that's the time that passed between ticks and it doesn't seems to change with the slider

**Review by agustinesco — APPROVED** [review]
LGTM! i tested it again and worked like a charm! idk what happened in my previous testing, maybe some compilation error

**Pull request merged**
