### PR TITLE
[GH-479] Change calls for casts

### LINKED ISSUE #497: [REFACTOR] Use cast instead of call
Image

Image

### PR DESCRIPTION
**Pull request by manucamejo**
Closes #497 

Use cast instead of calls for move, attack and use item, because we are not expecting any response.
We keep call in the join message because we are using that response.

### CODE REVIEW

**Review by Nico-Sanchez — COMMENTED** [review]
Is this properly tested? maybe we could run some loadtests using this, to see if this degrades our performance.
Generally speaking, a cast is better for scenarios where you don't want a reply, but maybe the sync call task is preventing some parts of our code to overload.
It's just an idea, I agree that cast seems a better option, but we could check it doing a loadtest with this changes.

**Comment by manucamejo** [comment]
Yesterday I did a load test (1000 players) and it works fine!

**Comment by Nico-Sanchez** [comment]
> Yesterday I did a load test (1000 players) and it works fine!

Can you attach some pictures regarding the server use (specially cpu usage)?
If you don't have any but you checked it and remember the number is fine as well. I just want to make sure that it stays the same (or better) than before.

**Comment by manucamejo** [comment]
Yeah, I did it again, here is the video
https://github.com/lambdaclass/mirra_backend/assets/20927859/fbc688e2-fc55-430a-832d-623cc6d655c7

**Review by Nico-Sanchez — APPROVED** [review]

**Review by agustinesco — APPROVED** [review]
LGTM!

**Pull request merged**
