### PR TITLE
Update README

### PR DESCRIPTION
**Pull request by Nico-Sanchez**
## Motivation

README was clearly outdated, devenv wasn't even working without yourself installing some tools.

## Summary of changes

- [Add nodejs in devenv nix packages](https://github.com/lambdaclass/mirra_backend/commit/89f03e7cbc01770677549ae6e63fe3a9f23d32d9)
- [Add requirements and start topics in README and update its commands](https://github.com/lambdaclass/mirra_backend/commit/e255b48ff2f98d530803faec80e492fda8242f04)

## Checklist
- [x] Tested the changes locally.
- [x] Reviewed the changes on GitHub, line by line.
- [x] This change requires new documentation.
  - [x] Documentation has been added/updated.

### CODE REVIEW

**Review by agustinesco — APPROVED** [review]
LGTM

**Review by agustinesco — CHANGES_REQUESTED** [review]
I think we should include the proto installation in the main readme, even tho it's in the arena app it's a bit hidden and we may miss that instalation and it's important to work with proto

```
### install protobuf
`brew install protobuf`
### install elixir protobuf plugin
`mix escript.install hex protobuf`

If you're using asdf to install elixir you need to run `asdf reshim` after this step

### Install protoc js
`npm install -g protoc-gen-js`
```

**Comment by Nico-Sanchez** [comment]
> I think we should include the proto installation in the main readme, even tho it's in the arena app it's a bit hidden and we may miss that instalation and it's important to work with proto
> 
> ```
> ### install protobuf
> `brew install protobuf`
Shouldn't this be a package in Nix?

> ### install elixir protobuf plugin
> `mix escript.install hex protobuf`
You ran this command inside devenv?

> If you're using asdf to install elixir you need to run `asdf reshim` after this step
> 
> ### Install protoc js
> `npm install -g protoc-gen-js`
> ```
What about this one?

I'll do a brief research and try myself but I would like to know your experience.

**Comment by agustinesco** [comment]
> Shouldn't this be a package in Nix?
Yeah! sorry i forgot that everything should be inside nix 😅  

> You ran this command inside devenv?
nope i ran it outside of devenv to be able to run the proto generation outside of it , also if you try to run the protos inside devenv you get an error:
```
protoc \
	--elixir_out=apps/gateway/lib/gateway/serialization \
	--elixir_opt=package_prefix=gateway.serialization \
	--proto_path=apps/serialization \
	gateway.proto
ERROR! Failed to start Elixir.
error: {error,
           {elixir,
               {{shutdown,
                    {failed_to_start_child,elixir_code_server,
                        {'EXIT',
                            {undef,
                                [{elixir_code_server,start_link,[],[]},
                                 {supervisor,do_start_child_i,3,
                                     [{file,"supervisor.erl"},{line,420}]},
                                 {supervisor,do_start_child,2,
                                     [{file,"supervisor.erl"},{line,406}]},
                                 {supervisor,'-start_children/2-fun-0-',3,
                                     [{file,"supervisor.erl"},{line,390}]},
                                 {supervisor,children_map,4,
                                     [{file,"supervisor.erl"},{line,1256}]},
                                 {supervisor,init_children,2,
                                     [{file,"supervisor.erl"},{line,350}]},
                                 {gen_server,init_it,2,
                                     [{file,"gen_server.erl"},{line,851}]},
                                 {gen_server,init_it,6,
                                     [{file,"gen_server.erl"},
                                      {line,814}]}]}}}},
                {elixir,start,[normal,[]]}}}}
```

> What about this one?
i couldn't test the js section since i can't get there 😅 due to the previous error

**Comment by Nico-Sanchez** [comment]
> > Shouldn't this be a package in Nix?
> 
> Yeah! sorry i forgot that everything should be inside nix 😅
> 
> > You ran this command inside devenv?
> 
> nope i ran it outside of devenv to be able to run the proto generation outside of it , also if you try to run the protos inside devenv you get an error:
> 
> ```
> protoc \
> 	--elixir_out=apps/gateway/lib/gateway/serialization \
> 	--elixir_opt=package_prefix=gateway.serialization \
> 	--proto_path=apps/serialization \
> 	gateway.proto
> ERROR! Failed to start Elixir.
> error: {error,
>            {elixir,
>                {{shutdown,
>                     {failed_to_start_child,elixir_code_server,
>                         {'EXIT',
>                             {undef,
>                                 [{elixir_code_server,start_link,[],[]},
>                                  {supervisor,do_start_child_i,3,
>                                      [{file,"supervisor.erl"},{line,420}]},
>                                  {supervisor,do_start_child,2,
>                                      [{file,"supervisor.erl"},{line,406}]},
>                                  {supervisor,'-start_children/2-fun-0-',3,
>                                      [{file,"supervisor.erl"},{line,390}]},
>                                  {supervisor,children_map,4,
>                                      [{file,"supervisor.erl"},{line,1256}]},
>                                  {supervisor,init_children,2,
>                                      [{file,"supervisor.erl"},{line,350}]},
>                                  {gen_server,init_it,2,
>                                      [{file,"gen_server.erl"},{line,851}]},
>                                  {gen_server,init_it,6,
>                                      [{file,"gen_server.erl"},
>                                       {line,814}]}]}}}},
>                 {elixir,start,[normal,[]]}}}}
> ```
> 
> > What about this one?
> 
> i couldn't test the js section since i can't get there 😅 due to the previous error

I talked with the team and this never worked. So I added the docs and lock files to install and run protobuf from root folder.

**Review by agustinesco — APPROVED** [review]
LGTM!

**Review by manucamejo — APPROVED** [review]

**Pull request merged**
